# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

# After adding/removing a plugin do: `sheldon lock --update`

shell = "zsh"

[plugins]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"
use = ["powerlevel10k.zsh-theme"]

[plugins.fzf]
github = "junegunn/fzf"
dir = "shell"
use = ["key-bindings.zsh", "completion.zsh"]

[plugins.zoxide]
github = "ajeetdsouza/zoxide"
hooks.post = "eval \"$(zoxide init zsh)\""

[plugins.asdf]
local = "~/.dotfiles/zsh/sheldon"
use = ["asdf.zsh"]

# fzf-tab plugin (must be loaded after compinit but before plugins that wrap widgets)
[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

# [plugins.iterm]
# local = "~/.dotfiles/zsh/sheldon"
# use = ["iterm.zsh"]