# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

# After adding/removing a plugin do: `sheldon lock --update`

shell = "zsh"

[plugins]

# Critical plugins that should load early
[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"
use = ["powerlevel10k.zsh-theme"]
apply = ["source"]

# Version managers with lazy-loading
[plugins.asdf]
local = "~/.dotfiles/zsh/sheldon"
use = ["asdf.zsh"]
apply = ["source"]

[plugins.pyenv]
local = "~/.dotfiles/zsh/sheldon"
use = ["pyenv.zsh"]
apply = ["source"]

# Directory navigation with immediate loading
[plugins.zoxide]
github = "ajeetdsouza/zoxide"
hooks.post = '''
if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init zsh --hook prompt)" >/dev/null 2>&1
fi
'''

# Terminal appearance and behavior
[plugins.terminal-title]
local = "~/.dotfiles/zsh/sheldon"
use = ["terminal-title.zsh"]
apply = ["source"]

# Tools with deferred loading
[plugins.direnv]
inline = '''
if command -v direnv >/dev/null 2>&1; then
  # Silence direnv during startup
  export DIRENV_LOG_FORMAT=""
  
  # Initialize direnv silently
  eval "$(direnv hook zsh)"
  
  # Define a function to re-enable direnv logging after first prompt
  function _direnv_enable_logging() {
    # Run only once
    precmd_functions=(${precmd_functions:#_direnv_enable_logging})
    
    # Restore standard logging format
    export DIRENV_LOG_FORMAT="direnv: %s"
  }
  
  # Add to precmd hooks to run after first prompt
  precmd_functions+=(_direnv_enable_logging)
fi
'''

[plugins.thefuck]
inline = '''
if command -v thefuck >/dev/null 2>&1; then
  eval "$(thefuck --alias f)" >/dev/null 2>&1
fi
'''

# FZF and related plugins (load in correct order)
[plugins.fzf]
github = "junegunn/fzf"
dir = "shell"
use = ["key-bindings.zsh", "completion.zsh"]

# fzf-tab must be loaded after compinit but before plugins that wrap widgets
[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
apply = ["source"]

[plugins.fzf-tab-config]
local = "~/.dotfiles/zsh/sheldon"
use = ["fzf-tab-config.zsh"]
apply = ["source"]
hooks.pre = '''
# Enable caching for better completion performance
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "$HOME/.zcompcache"
'''

# Syntax highlighting and autosuggestions (load last for best performance)
[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
apply = ["source"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["source"]


[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["source"]


# Optional iTerm integration (commented out by default)
# [plugins.iterm]
# local = "~/.dotfiles/zsh/sheldon"
# use = ["iterm.zsh"]